[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    positive: Позитивные тесты
    negative: Негативные тесты
    smoke: Smoke тесты
    regression: Регрессионные тесты
    ui: UI тесты
    api: API тесты
    slow: Медленные тесты
    critical: Критически важные тесты
addopts = -v --strict-markers -p no:warnings